INSERT INTO java_topics(id, name) VALUES (0,'Datatypes');
INSERT INTO java_topics(id, name) VALUES (1,'Variables');
INSERT INTO java_topics(id, name) VALUES (2,'Operators');
INSERT INTO java_topics(id, name) VALUES (3,'Control Statements');
INSERT INTO java_topics(id, name) VALUES (4,'Methods');
INSERT INTO java_topics(id, name) VALUES (5,'Arrays');
INSERT INTO java_topics(id, name) VALUES (6,'Classes');
INSERT INTO java_topics(id, name) VALUES (7,'Inheritance');
INSERT INTO java_topics(id, name) VALUES (8,'Methods Overriding, Overloading');
INSERT INTO java_topics(id, name) VALUES (9,'Abstract Class And Methods');
INSERT INTO java_topics(id, name) VALUES (10,'Interfaces, Packages and Access Control');
INSERT INTO java_topics(id, name) VALUES (11,'final, static and others');
INSERT INTO java_topics(id, name) VALUES (12,'Exceptions');
INSERT INTO java_topics(id, name) VALUES (13,'Multithreaded Programming');
INSERT INTO java_topics(id, name) VALUES (14,'Generics');
INSERT INTO java_topics(id, name) VALUES (15,'Strings');
INSERT INTO java_topics(id, name) VALUES (16,'java.lang');
INSERT INTO java_topics(id, name) VALUES (17,'Collections Framework');
INSERT INTO java_topics(id, name) VALUES (18,'Utility Classes');
INSERT INTO java_topics(id, name) VALUES (19,'Input/Output');
INSERT INTO java_topics(id, name) VALUES (20,'The Applet Class');
INSERT INTO java_topics(id, name) VALUES (21,'Swing');
INSERT INTO java_topics(id, name) VALUES (22,'Servlets');
